name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # or any other Node.js version you're using

    - name: Install Dependencies
      run: npm install

    - name: Build Svelte App
      run: npm run build
      # This builds your Svelte app

    - name: Install pkg
      run: npm install -g pkg

    - name: Generate Binary
      run: pkg . --out-path dist/
      # This assumes you have a pkg configuration in your package.json or a separate config file

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-1' # Use your AWS region

    - name: Upload the binary to Amazon S3
      run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/dist/my-svelte-app.exe --acl public-read
